### ISSUE TITLE
Container log improvements (1/n)

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi#239]
Make the following improvements to container logs:
- Fetch container logs from both current and previous deployment (will require a `uffizzi_controller` change)   
- Remove quotes around log output in our UI  
- Add support for rendering ANSI escape color codes  

![Screen Shot 2022-08-24 at 1 31 07 PM](https://user-images.githubusercontent.com/7218230/186495980-e1603590-223a-425d-99fd-22c201520a3a.png)

![Screen Shot 2022-08-24 at 1 29 34 PM](https://user-images.githubusercontent.com/7218230/186495637-acf0ae88-eaaa-4824-b127-11b841196636.png)

**Comment by waveywaves** [comment]
Can we also change the logs to a monospaced font, it would be more developer friendly

**Comment by axisofentropy** [comment]
@gadkins We might want a little design for how the current and previous containers should be displayed. Maybe toggle between? Or combined but with a clear delineation between? There should be at least a little visual separation.

**Comment by axisofentropy** [comment]
Depends upon https://github.com/UffizziCloud/uffizzi_controller/issues/30

**Comment by gadkins** [comment]
Duplicate of https://github.com/UffizziCloud/uffizzi_platform/issues/419
