### ISSUE TITLE
Improve message if uffizzi unable to log in to docker registry.

### ISSUE THREAD

**Issue by NealArw** [UffizziCloud/uffizzi#264]
1. Go into CLI
2. Sign in
3. Try to connect any docker-registry (ecr, acr, etc..) using invalid credentials (run: `bundle exec uffizzi connect docker-hub`)

**Result:** 
Message: `We were unable to log you in to docker registry. Please verify that your username and password are correct.`

**Suggestion:** Specify which docker registry we can't log in to.
In GHA it is hard to understand, which connection was failed:

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/89470900/190434284-0056582d-e001-4a63-89bc-dec788bed2cb.png">

**Comment by JessikaCastellano** [comment]
Test result:

![2022-09-27_18-32](https://user-images.githubusercontent.com/37912327/192650081-459c1517-e4f9-45a6-9614-3c15815e1ceb.png)

**Comment by moklidia** [comment]
@JessikaCastellano Please test and attach screenshots of cases when a custom docker registry is used.

**Comment by JessikaCastellano** [comment]
**Tests**

**_DockerHub:_**
![2022-10-03_07-50-docker-hub](https://user-images.githubusercontent.com/37912327/193603025-28089af2-ddb1-443f-b423-33e9df221988.png)

**_Azure:_**
![2022-10-03_09-04-azure](https://user-images.githubusercontent.com/37912327/193603121-83758f4d-b684-4f4a-ab3e-b3185a8ec30c.png)

**_Amazon:_**
![2022-10-03_09-06-amazon](https://user-images.githubusercontent.com/37912327/193603164-5d8977f1-62ec-42bf-ac3d-1b58b84a4ba5.png)

**_Google:_**
![2022-10-03_09-14-google](https://user-images.githubusercontent.com/37912327/193603204-e6a5e584-c51e-47f1-9099-af2f522d8ab6.png)

**_GitHub Container Registry_**
![2022-10-03_09-19-github-container](https://user-images.githubusercontent.com/37912327/193603268-30c41ea2-28b5-4bc4-ab08-8fe675719001.png)

**Comment by JessikaCastellano** [comment]
**Docker Registry:**

![2022-10-03_13-52-docker-registry](https://user-images.githubusercontent.com/37912327/193681940-226ae7d5-3d1f-49a3-ad05-5024dfe81c8a.png)

**Comment by moklidia** [comment]
@JessikaCastellano The objective of this task is not achieved - please look up the description

https://github.com/UffizziCloud/uffizzi_app/issues/264#issue-1381374784

**Comment by JessikaCastellano** [comment]
New [PR #283](https://github.com/UffizziCloud/uffizzi_app/pull/283) open 

Tests:

**DockerHub**
![2022-10-07_16-30-docker-hub](https://user-images.githubusercontent.com/37912327/194651960-d2381d14-a808-4364-b010-34bd9c19aae9.png)

**Azure**
![2022-10-07_16-50-azure](https://user-images.githubusercontent.com/37912327/194651989-17b35eb3-8979-472f-a39d-3d491f87c7a0.png)

**Amazon**
![2022-10-07_16-51-amazon](https://user-images.githubusercontent.com/37912327/194652003-e23893d8-9f14-40ae-94a3-2b29b6554e69.png)


**Google**
![2022-10-07_16-52-google](https://user-images.githubusercontent.com/37912327/194652028-73927b74-6823-4319-8efa-eb579e880104.png)

**GitHub Container Registry**
![2022-10-07_16-53-ghcr](https://user-images.githubusercontent.com/37912327/194652152-8f5ff0cc-2f31-44be-ab74-2a681667a4b1.png)

**Docker Registry**
![2022-10-07_16-54-docker-registry](https://user-images.githubusercontent.com/37912327/194652238-4b93ae1b-c666-4e2f-ab42-e3f8da85598b.png)

**Comment by NealArw** [comment]
**TESTED on prod - OK**

```
# uffizzi connect gcr google.json
We were unable to log you in to Google. Please verify that your username and password are correct.

# uffizzi connect docker-hub
Username: 12351
Password:
We were unable to log you in to DockerHub. Please verify that your username and password are correct.

# uffizzi connect ecr
Registry Domain: ***
Access key ID: c1234c
Secret access key:
We were unable to log you in to Amazon. Please verify that your username and password are correct.

# uffizzi connect ghcr
Github Username: NealArw
Access Token:
We were unable to log you in to Github Container Registry. Please verify that your username and password are correct.
```

For `docker-registry` issue created https://github.com/UffizziCloud/uffizzi/issues/295
