### ISSUE TITLE
Automatically Delete Kubernetes Resources for Deployments in failed State

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi#269]
Origin issue https://github.com/UffizziCloud/uffizzi_platform/issues/201

**Comment by jpthurman** [comment]
@JessikaCastellano @moklidia @zipofar 

We should keep `failed` deployments for 1 hour before auto-deleting them - this way the user will have the logs in the window they are most likely troubleshooting.  This should give users enough time to troubleshoot.  

Let's get an acceptable, working solution out now that will work for majority of users.

**Comment by NealArw** [comment]
Returned with https://github.com/UffizziCloud/uffizzi_platform/issues/201

**Comment by NealArw** [comment]
Returned with https://github.com/UffizziCloud/uffizzi_platform/issues/201
