### ISSUE TITLE
Container service refactoring

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi#278]
Bind with https://github.com/UffizziCloud/uffizzi_platform/issues/306

**Comment by NealArw** [comment]
1. Can't add compose file/create deployemnt:

The message that credentials/image not found should be shown

- [ ] docker-hub private image, integration was not connected
- [ ] google, integration was not connected
- [ ] amazon, integration was not connected
- [ ] azure, integration was not connected
- [ ] ghcr, integration was not connected

```
bash-5.1# bundle exec uffizzi preview create test-compose/uffizzi-compose-webhook-docker-private.yml
Internal Server Error
```
