### ISSUE TITLE
Logs (1/n) Basic formatting

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi#299]
Refer to this issue: https://github.com/UffizziCloud/uffizzi_platform/issues/455

**Comment by fedorov-dualboot** [comment]
tested. **Fixed.**
![image](https://user-images.githubusercontent.com/110913994/202694785-cffa686f-1aec-4014-b5fe-9c9c6532d08f.png) 
![image](https://user-images.githubusercontent.com/110913994/202699730-400cd727-1c81-4f25-a4a7-0768fe09b3f1.png)

**Comment by fedorov-dualboot** [comment]
verified on prod. **OK** 
![image](https://user-images.githubusercontent.com/110913994/203072759-73bcda07-463f-4505-8074-1244dcbc7626.png)
![image](https://user-images.githubusercontent.com/110913994/203072894-4b5d5298-0654-464f-8acf-bfb321cd3a1f.png)
