### ISSUE TITLE
Errors aren't rescued in check_credentials when compose file contains mistakes

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi#309]
https://sentry.io/organizations/uffizzi-cloud/issues/3741584395/?project=1826818&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h

**Comment by antlu** [comment]
Test on platform
https://github.com/UffizziCloud/uffizzi_platform/issues/527#issuecomment-1327423778

**Comment by NealArw** [comment]
**Not relevant**
