### ISSUE TITLE
Add default Uffizzi variables to environments

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi#314]
We already have UFFIZZI_URL available in each container, but it would be useful to add more standard vars, like deployment id, server domain, project/account id.

**Comment by moklidia** [comment]
@gadkins which variables do you think would be useful for users?

**Comment by gadkins** [comment]
@moklidia This is a better question for @waveywaves @ShrutiC-git @daramayis or @axisofentropy

**Comment by ShrutiC-git** [comment]
Not sure what the use of adding other variables aside from the URL be for the users, @moklidia. Exposing the URL to the containers makes sense but I can't think of any other variable that would be needed. Do you have a case in mind that we could apply it to?

**Comment by daramayis** [comment]
I think the following will be helpful.
- UFFIZZI_URL w/o protocol — in several cases I should clean up the protocol from `UFFIZZI_URL`.

I faced a similar problem a few times.

**Comment by NealArw** [comment]
**TESTED - OK**

```
    Environment:
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  postgres
      PORT:               80
      UFFIZZI_URL:        https://deployment-6-default.app.qa-gke.uffizzi.com
      UFFIZZI_DOMAIN:     deployment-6-default.app.qa-gke.uffizzi.com
```

**Comment by NealArw** [comment]
**TESTED on prod - OK**

```
- name: UFFIZZI_URL
value: https://deployment-8101-hello-world-1-e8kf.app.uffizzi.com/
- name: UFFIZZI_DOMAIN
value: deployment-8101-hello-world-1-e8kf.app.uffizzi.com
```
