### ISSUE TITLE
Investigate much retries

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi#328]
![Screenshot 2022-11-30 at 11 21 00](https://user-images.githubusercontent.com/22678201/204744378-576a98c8-9503-47ae-8e0a-864f5800fc06.png)

**Comment by NealArw** [comment]
**TESTED - OK**
https://github.com/UffizziCloud/uffizzi_platform/issues/604#issuecomment-1350588336

**Comment by NealArw** [comment]
**TESTED on prod - OK**
https://github.com/UffizziCloud/uffizzi_platform/issues/604
