### ISSUE TITLE
Nullify `deployed_by_id` if the user removed

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi#353]
If the user got removed, the deployed_by_id in deployments points to the id of the user that no longer exists. Need to add the `dependent :nullify` strategy.

**Comment by NealArw** [comment]
**TESTED on prod - OK**

**Comment by NealArw** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/216330310-f787c649-56ce-497f-847d-1b58368e8f1a.png">
