### ISSUE TITLE
Phase 3 Billing: add the pull request link to the persistent banner

### ISSUE THREAD

**Issue by antlu** [UffizziCloud/uffizzi#359]
Required by https://github.com/UffizziCloud/uffizzi_platform/issues/677

**Comment by antlu** [comment]
Test in platform #677

**Comment by fedorov-dualboot** [comment]
**OK.** tested as part https://github.com/UffizziCloud/uffizzi_platform/issues/677.

**Comment by NealArw** [comment]
Was not released on prod.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/215718698-45ba99cb-7dc5-4094-b52c-c0a7d5f1235b.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/215718760-48b5dadb-f325-4266-a1d5-7bc2340215d3.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/215719905-144029dc-0263-46d7-a6d1-ef092c04ee4a.png">

**Comment by NealArw** [comment]
TESTED on prod - OK

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/216332657-ef0f4256-6b87-45ec-bac1-6470e52e9c4c.png">
