### ISSUE TITLE
Add UFFIZZI_PREDICTABLE_URL as a default container variable

### ISSUE THREAD

**Issue by greenfrontend** [UffizziCloud/uffizzi#367]
Add the UFFIZZI_PREDICTABLE_URL to each container as a default container variable in the same way as the UFFIZZI_URL variable

**Comment by fedorov-dualboot** [comment]
tested as part https://github.com/UffizziCloud/uffizzi_platform/issues/745

**Comment by fedorov-dualboot** [comment]
verified on prod. **OK**
![image](https://user-images.githubusercontent.com/110913994/216347675-d3f61370-3415-4769-9732-ae4c7a36f318.png)
