### ISSUE TITLE
BUG: undefined method - each_with_object

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi#399]
https://uffizzi-cloud.sentry.io/issues/3919773378/?project=1826818&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=6

### How To Test:###
* Try to deploy empty compose file (expected error)
* Try to deploy compose file just with string, like a `some text` (expected error)

**Comment by NealArw** [comment]
Empty file:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/230897335-5866de1e-9f5c-4eaa-b8f9-e08143479805.png">

File with only one string:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/230897450-c77409cd-0da4-4e43-ad36-164be7f4ab77.png">

**Comment by NealArw** [comment]
Empty file:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/230943275-8b0779c5-53b1-4c52-bbf2-860e5973bca8.png">

File with only one string:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/230944390-e998ea63-f9b2-4b36-a791-b56a2e91e1a9.png">

**Comment by NealArw** [comment]
**TESTED - OK**
