### ISSUE TITLE
Set a Resource cap of 8Gb RAM for deployments

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi#443]
Do not let platform users use more than 8Gb RAM for one deployment. Open-source users should be able to request as much memory as they want.

**Comment by ALEXANCHESSS** [comment]
The line break didn't work in the error message
<img width="593" alt="image" src="https://github.com/UffizziCloud/uffizzi/assets/91793094/919b67a9-38ff-44d6-a0ba-2e7bda13b7c5">

**Comment by ALEXANCHESSS** [comment]
Cut the check "requested memory"
<img width="673" alt="image" src="https://github.com/UffizziCloud/uffizzi/assets/91793094/b047db1b-05aa-4646-9c9f-d05df177f697">

**Comment by ALEXANCHESSS** [comment]
**TESTED - OK**
<img width="645" alt="image" src="https://github.com/UffizziCloud/uffizzi/assets/91793094/4ab04763-1c6b-4e44-8a5e-05167ae63ad3">
