### ISSUE TITLE
Add user account metadata to uclusters

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi#509]
Add the user account ID to ucluster metadata to assist with filtering and troubleshooting

**Comment by moklidia** [comment]
Tested locally:
<img width="1512" alt="Снимок экрана 2024-05-23 в 22 14 01" src="https://github.com/UffizziCloud/uffizzi/assets/42300552/f1438dd3-460a-4e28-b5c5-fcb5aecd5df8">
